import { createElement } from "react";
import { createRoot } from "react-dom/client";
import App from "../src/App";
import { frame, picture, settle } from "./editing-tools";
import "../src/styles.css";

const reports: string[] = [];
const check = (value: boolean, message: string) => { if (!value) throw new Error(message); reports.push(`PASS ${message}`); };
const host = document.getElementById("test-root")!;
const root = createRoot(host);
const paint = async () => { await frame(); await frame(); };
const button = (label: string) => host.querySelector<HTMLButtonElement>(`button[aria-label="${label}"]`)!;
const zoom = () => host.querySelector("output[aria-label='当前缩放比例']")!.textContent;
const viewport = () => host.querySelector<HTMLElement>(".canvas-viewport")!;
try {
  root.render(createElement(App));
  await settle(() => !!button("收起图层") && !button("收起图层").disabled && button("消除笔").getAttribute("aria-pressed") === "true");
  const settings = () => host.querySelector<HTMLElement>(".settings-panel")!;
  const settingsHidden = () => getComputedStyle(settings()).display === "none";
  const initialWidth = viewport().clientWidth;
  check(!settingsHidden() && !host.querySelector(".tip-card") && button("消除笔").getAttribute("aria-pressed") === "true", "初始选中消除笔并展开属性，不显示常驻说明卡片");
  check([...host.querySelectorAll<HTMLButtonElement>("button")].find(item => item.textContent === "开始消除")!.disabled && host.querySelector<HTMLButtonElement>(".top-right .primary-button")!.disabled && button("撤销").disabled, "默认消除模式无选区、不处理图片、不产生草稿修改");
  const eraseZoom = zoom();
  for (const mode of ["选择", "平移"]) {
    button(mode).click(); await paint();
    check(!!button("返回消除笔") && !settings().querySelector(".canvas-mode-hint") && !settings().querySelector(".erase-mode-grid") && settings().textContent!.includes("已保留的消除设置"), `消除切${mode}显示单一模式说明、返回入口和设置摘要`);
    button("返回消除笔").click(); await paint();
    check(!!settings().querySelector(".erase-mode-grid") && !settings().querySelector(".erase-paused") && viewport().clientWidth === initialWidth && zoom() === eraseZoom && button("撤销").disabled, `从${mode}返回消除保持面板尺寸、缩放及历史`);
  }
  const eraseCanvas = host.querySelector<HTMLCanvasElement>(".upper-canvas")!;
  eraseCanvas.dispatchEvent(new KeyboardEvent("keydown", { key: " ", code: "Space", bubbles: true, cancelable: true })); await paint();
  check(!!settings().querySelector(".erase-mode-grid") && !settings().querySelector(".erase-paused"), "按住空格临时平移不切换消除面板");
  window.dispatchEvent(new KeyboardEvent("keyup", { key: " ", code: "Space", bubbles: true }));
  const help = button("操作帮助");
  const helpTip = () => document.getElementById(help.getAttribute("aria-describedby") ?? "");
  const delay = () => new Promise(resolve => setTimeout(resolve, 360));
  help.focus({ preventScroll: true }); await paint();
  const hintBox = helpTip()!.getBoundingClientRect(), helpBox = help.getBoundingClientRect();
  check(helpTip()!.textContent === "操作说明与快捷键" && Math.abs(hintBox.left - helpBox.right - 8) < 1 && Math.abs(hintBox.top + hintBox.height / 2 - helpBox.top - helpBox.height / 2) < 1, "帮助提示文案对应内容，紧贴按钮右侧并垂直居中");
  help.click(); await paint();
  check(!!host.querySelector("dialog[open] #shortcut-help-title") && !settingsHidden() && viewport().clientWidth === initialWidth && !helpTip(), "打开帮助立即隐藏提示，不改变属性栏或画布布局");
  host.querySelector("dialog")!.dispatchEvent(new Event("cancel", { bubbles: false, cancelable: true })); await paint();
  await delay();
  check(!host.querySelector(".shortcut-help-dialog") && document.activeElement === help && !helpTip(), "Esc 取消帮助返回入口焦点，等待后也不残留提示");
  help.blur(); help.focus({ preventScroll: true }); await paint();
  check(!!helpTip(), "键盘重新聚焦帮助入口可再次显示提示");
  help.click(); await paint(); button("关闭操作帮助").click(); await paint(); await delay();
  check(document.activeElement === help && !helpTip(), "关闭按钮返回帮助入口后不残留提示");
  help.dispatchEvent(new MouseEvent("mouseover", { bubbles: true, relatedTarget: document.body })); await delay();
  check(!helpTip(), "弹窗关闭后的悬停恢复不会自动显示提示");
  help.blur();
  window.dispatchEvent(new PointerEvent("pointermove", { clientX: helpBox.right + 30, clientY: helpBox.top, bubbles: true }));
  help.dispatchEvent(new MouseEvent("mouseover", { bubbles: true, relatedTarget: document.body })); await paint();
  check(!helpTip(), "鼠标重新移入时短暂停留后才显示提示");
  await settle(() => !!helpTip());
  check(!!helpTip(), "鼠标移开再移入帮助入口可再次显示提示");
  help.dispatchEvent(new MouseEvent("mouseout", { bubbles: true, relatedTarget: document.body })); await paint();
  check(!helpTip(), "移开帮助入口立即隐藏提示");
  button("收起工具属性").click(); await paint();
  const openingWidth = viewport().clientWidth, openingZoom = zoom();
  check(settingsHidden() && openingWidth > initialWidth, "默认消除笔面板仍可手动收起以释放空间");
  const centerPixels = () => {
    const surface = host.querySelector<HTMLCanvasElement>(".lower-canvas")!;
    return surface.getContext("2d")!.getImageData(Math.floor(surface.width / 2) - 10, Math.floor(surface.height / 2) - 10, 20, 20).data;
  };
  const centerBefore = centerPixels();
  button("绘制").click(); await paint();
  const centerAfter = centerPixels();
  check(!settingsHidden() && viewport().clientWidth < openingWidth && zoom() === openingZoom, "点击工具展开属性，保持原有缩放");
  check(centerBefore.every((value, i) => Math.abs(value - centerAfter[i]) <= 2), "属性展开保持画布中心对应的图片内容");
  button("选择").click(); await paint();
  check(!settingsHidden() && settings().textContent!.includes("新画笔样式") && button("绘制").getAttribute("aria-pressed") === "true" && button("选择").getAttribute("aria-pressed") === "true", "进入选择模式后保留绘制工作区与新画笔样式，两处高亮分别表达工作区和鼠标操作");
  button("收起工具属性").click(); await paint();
  check(settingsHidden() && viewport().clientWidth === openingWidth && zoom() === openingZoom && document.activeElement === viewport(), "手动收起释放空间并将焦点移回画布");
  button("绘制").click(); await paint();
  button("收起工具属性").click(); await paint();
  button("绘制").click(); await paint();
  check(!settingsHidden() && button("绘制").getAttribute("aria-pressed") === "true", "再次点击当前工具可展开属性，不需切换工具");
  check(!host.querySelector(".top-actions")!.textContent!.includes("上传") && host.querySelector(".top-right .upload-button")!.textContent === "上传本地图片", "上传入口移至右上角，名称明确本地来源");
  check(host.querySelector(".top-right .upload-button")!.getAttribute("aria-describedby") !== null && host.querySelector(".top-right")!.textContent!.includes("暂不替换任务图片"), "上传说明区分载入草稿和提交任务");
  check(host.querySelectorAll(".canvas-controls .zoom-control > [role=group]").length === 4, "底部操作按模式、缩放、对比、图层分组");
  check([...host.querySelectorAll(".top-actions button")].map(item => item.getAttribute("aria-label")).join("/") === "撤销/重做/还原初始/按住查看原图" && [...host.querySelectorAll(".top-actions button")].every(item => !item.textContent), "左上角按顺序显示四个纯图标按钮");
  check(button("100% 查看").textContent === "100%" && !!button("按住查看原图").querySelector("svg") && !button("按住查看原图").textContent && !button("收起图层").textContent, "对比和图层仅用图标，100% 保留数字");
  const width = viewport().clientWidth, initialZoom = zoom();
  button("收起图层").click(); await paint();
  check(getComputedStyle(host.querySelector(".layers-panel")!).display === "none" && viewport().clientWidth > width && zoom() === initialZoom, "收起图层实际释放空间，适配状态下也保持缩放比例");
  button("绘制").click(); await paint();
  check(!!button("展开图层"), "切换工具不自动展开图层");
  button("文字").click(); await paint();
  const canvas = host.querySelector<HTMLCanvasElement>(".upper-canvas")!;
  button("添加文字").click();
  await settle(() => !!host.querySelector(".layer-card.selected[data-purpose=content]"));
  check(!!button("展开图层"), "新增文字不自动展开图层");
  const selectedLayer = host.querySelector(".layer-card.selected");
  const textZoom = zoom(), textWidth = viewport().clientWidth;
  const emptyBounds = canvas.getBoundingClientRect();
  for (const type of ["mousedown", "mouseup"]) (type === "mousedown" ? canvas : document).dispatchEvent(new MouseEvent(type, {
    bubbles: true, cancelable: true, button: 0, buttons: type === "mousedown" ? 1 : 0,
    clientX: emptyBounds.left + 8, clientY: emptyBounds.top + 8,
  }));
  await paint();
  check(!host.querySelector(".layer-card.selected") && !settingsHidden() && settings().textContent!.includes("新文字样式") && !settings().querySelector(".settings-empty") && button("文字").getAttribute("aria-pressed") === "true", "添加文字后点图片外空白处，取消选择但继续停留文字工作区");
  check(viewport().clientWidth === textWidth && zoom() === textZoom && host.querySelectorAll('.layer-card[data-purpose=content]').length === 1, "结束文字编辑不新增对象、不改变布局和缩放");
  selectedLayer!.querySelector<HTMLButtonElement>(".layer-select")!.click(); await paint();
  check(settings().textContent!.includes("当前文字属性") && host.querySelector(".layer-card.selected") === selectedLayer, "重新选择已有文字显示当前属性");
  button("收起工具属性").click(); await paint();
  check(settingsHidden() && host.querySelector(".layer-card.selected") === selectedLayer, "收起属性保留当前文字选择");
  button("操作帮助").click(); await paint();
  host.querySelector("dialog button")!.dispatchEvent(new KeyboardEvent("keydown", { key: "Delete", bubbles: true, cancelable: true })); await paint();
  check(host.querySelector(".layer-card.selected") === selectedLayer, "帮助弹窗内快捷键不误删画布对象");
  button("关闭操作帮助").click(); await paint();
  button("文字").click(); await paint();
  button("选择").click(); await paint();
  button("收起工具属性").click(); await paint();
  const selectionBounds = canvas.getBoundingClientRect();
  const selectPoint = { clientX: selectionBounds.left + selectionBounds.width / 2 + 10, clientY: selectionBounds.top + selectionBounds.height / 2 + 10 };
  canvas.dispatchEvent(new PointerEvent("pointerdown", { ...selectPoint, pointerId: 41, button: 0, buttons: 1, bubbles: true }));
  canvas.dispatchEvent(new MouseEvent("mousedown", { ...selectPoint, button: 0, buttons: 1, bubbles: true })); await paint();
  check(settingsHidden() && host.querySelector(".layer-card.selected") === selectedLayer, "画布按下选中文字时不立即展开属性或改变视野");
  window.dispatchEvent(new PointerEvent("pointerup", { pointerId: 42, button: 0, buttons: 0, bubbles: true }));
  window.dispatchEvent(new PointerEvent("pointerup", { pointerId: 41, button: 2, buttons: 1, bubbles: true })); await paint();
  check(settingsHidden(), "其他指针或右键松开不提前展开属性");
  document.dispatchEvent(new MouseEvent("mouseup", { ...selectPoint, button: 0, buttons: 0, bubbles: true }));
  window.dispatchEvent(new PointerEvent("pointerup", { ...selectPoint, pointerId: 41, button: 0, buttons: 0, bubbles: true })); await paint();
  check(!settingsHidden() && host.querySelector(".layer-card.selected") === selectedLayer, "左键松开后展示对象属性，保留选择和图层身份");
  button("展开图层").click(); await paint();
  check(viewport().clientWidth === width && zoom() === initialZoom && host.querySelector(".layer-card.selected") === selectedLayer, "展开恢复空间且保持文字选中状态");
  button("100% 查看").click(); await paint();
  button("收起图层").click(); await paint();
  check(zoom() === "100%", "实际尺寸查看时收起也不重新适配");
  const compare = button("按住查看原图");
  const held = () => compare.getAttribute("aria-pressed") === "true";
  const key = (type: string, value: string, repeat = false) => compare.dispatchEvent(new KeyboardEvent(type, { key: value, repeat, bubbles: true, cancelable: true }));
  compare.click(); await paint();
  check(!held(), "单击不会锁定原图查看状态");
  key("keydown", " "); await paint();
  check(held() && host.querySelector(".original-badge")!.textContent!.includes("松开返回编辑") && zoom() === "100%", "按住空格立即查看原图，同尺寸保持缩放并提示松开返回");
  const lowerCompare = host.querySelector<HTMLButtonElement>(".canvas-controls button[aria-label='按住查看原图']")!;
  check(lowerCompare.getAttribute("aria-pressed") === "true", "左上角按住查看时右下角入口同步高亮");
  key("keydown", " ", true); await paint();
  check(held(), "长按产生的重复按键不切换状态");
  button("展开图层").click(); await paint();
  key("keyup", " "); await paint();
  check(zoom() === "100%" && !host.querySelector(".original-badge"), "对比期间切换图层后仍可恢复编辑缩放");
  lowerCompare.dispatchEvent(new KeyboardEvent("keydown", { key: "Enter", bubbles: true, cancelable: true })); await paint();
  check(held() && lowerCompare.getAttribute("aria-pressed") === "true", "右下角入口也可开始查看，两处状态一致");
  lowerCompare.dispatchEvent(new KeyboardEvent("keyup", { key: "Enter", bubbles: true, cancelable: true })); await paint();
  check(!held() && lowerCompare.getAttribute("aria-pressed") === "false", "右下角松开后两处同步恢复");
  key("keydown", "Enter"); await paint();
  key("keyup", " "); await paint();
  check(held(), "无关按键松开不会结束 Enter 查看");
  key("keyup", "Enter"); await paint();
  check(!held(), "松开 Enter 恢复编辑");
  key("keydown", "Enter"); await paint(); window.dispatchEvent(new Event("blur")); await paint();
  check(!held(), "窗口失焦自动恢复编辑");
  compare.focus(); key("keydown", " "); await paint(); compare.blur(); await paint();
  check(!held(), "按钮失焦自动恢复编辑");
  // DOM-dispatched pointer events do not create native pointers; capture itself is checked manually in-browser.
  const capture = compare.setPointerCapture; compare.setPointerCapture = () => {};
  const pointer = (target: EventTarget, type: string, id = 7, mouseButton = 0, buttons = 0) => target.dispatchEvent(new PointerEvent(type, { pointerId: id, button: mouseButton, buttons, bubbles: true, cancelable: true }));
  try {
    pointer(compare, "pointerdown", 7, 0, 1); await paint();
    check(held(), "鼠标按下立即显示原图");
    pointer(window, "pointerup", 8); pointer(window, "pointerup", 7, 2, 1); await paint();
    check(held(), "其他指针或右键松开不会结束左键查看");
    pointer(window, "pointerup"); await paint();
    check(!held(), "移出按钮后松手恢复编辑");
    pointer(compare, "pointerdown", 7, 0, 1); await paint(); pointer(window, "pointercancel"); await paint();
    check(!held(), "指针取消恢复编辑");
    pointer(compare, "pointerdown", 7, 0, 1); await paint(); pointer(compare, "lostpointercapture"); await paint();
    check(!held(), "丢失指针捕获恢复编辑");
  } finally { compare.setPointerCapture = capture; }
  button("收起图层").focus(); await paint();
  check(getComputedStyle(button("收起图层").parentElement!.querySelector("[role=tooltip]")!).visibility === "visible", "图标按钮键盘聚焦时显示提示");
  host.style.width = "1000px"; await paint();
  const group = host.querySelector<HTMLElement>(".canvas-zoom-controls")!, zoomButtons = [...group.querySelectorAll("button")];
  check(zoomButtons.every(item => item.getBoundingClientRect().top === zoomButtons[0].getBoundingClientRect().top), "较窄空间中缩放组完整保留在同一行");
  const controls = host.querySelector<HTMLElement>(".canvas-controls")!.getBoundingClientRect();
  check([...host.querySelectorAll<HTMLElement>(".zoom-control button")].every(item => { const box = item.getBoundingClientRect(); return box.left >= controls.left && box.right <= controls.right; }), "较窄画布的操作按钮不溢出");
  host.style.width = ""; await paint();
  const fileInput = host.querySelector<HTMLInputElement>("input[type=file][accept='.jpg,.jpeg']")!;
  const upload = () => host.querySelector<HTMLButtonElement>(".upload-button")!;
  const confirmation = () => host.querySelector<HTMLDialogElement>(".confirmation-dialog");
  const chooseFile = async (file?: File) => {
    const files = new DataTransfer(); if (file) files.items.add(file);
    fileInput.files = files.files; fileInput.dispatchEvent(new Event("change", { bubbles: true })); await paint();
  };
  for (const collapsed of [false, true]) {
    button("调色").click(); await paint();
    if (collapsed) { button("收起工具属性").click(); await paint(); }
    const beforeSize = host.querySelector(".document-size")!.textContent;
    const beforeLayers = host.querySelector(".layers-panel")!.textContent;
    const originalState = () => button("调色").getAttribute("aria-pressed") === "true" && settingsHidden() === collapsed && host.querySelector(".document-size")!.textContent === beforeSize && host.querySelector(".layers-panel")!.textContent === beforeLayers;
    const image = new File([await picture("#67a9cf", collapsed ? 640 : 512, 384)], "upload.jpg");
    await chooseFile();
    check(originalState() && !confirmation(), `属性栏${collapsed ? "收起" : "展开"}时取消文件选择保持工具、布局和草稿`);
    await chooseFile(image); await settle(() => !!confirmation()?.open);
    confirmation()!.querySelector<HTMLButtonElement>(".secondary-button")!.click(); await paint();
    check(originalState(), `属性栏${collapsed ? "收起" : "展开"}时取消载入确认保持原状`);
    await chooseFile(new File(["invalid JPEG"], "broken.jpg")); await settle(() => !!confirmation()?.open);
    confirmation()!.querySelector<HTMLButtonElement>(".primary-button")!.click(); await paint();
    await settle(() => !confirmation() && !upload().disabled);
    check(originalState(), `属性栏${collapsed ? "收起" : "展开"}时上传无效文件保留工具、布局和草稿`);
    await chooseFile(image); await settle(() => !!confirmation()?.open);
    confirmation()!.querySelector<HTMLButtonElement>(".primary-button")!.click();
    await settle(() => !upload().disabled && button("消除笔").getAttribute("aria-pressed") === "true"); await paint();
    check(settingsHidden() === collapsed && settings().querySelector(".panel-heading")!.textContent!.includes("消除笔") && !settings().querySelector(".settings-empty"), `上传成功选中消除笔并保持属性栏${collapsed ? "收起" : "展开"}，不留下空白属性`);
    check(host.querySelector(".document-size")!.textContent === `${collapsed ? 640 : 512} × 384 px` && [...host.querySelectorAll<HTMLButtonElement>("button")].find(item => item.textContent === "开始消除")!.disabled && button("撤销").disabled, "新图按实际尺寸载入，无选区、不自动消除、旧历史已清空");
  }
  button("消除笔").click(); await paint();
  check(!settingsHidden(), "上传后再次点击消除笔仍可展开手动收起的属性栏");
  const ratioWidth = () => host.querySelector("output[aria-label='当前缩放比例']")!.getBoundingClientRect().width;
  const fixedWidth = ratioWidth();
  for (let i = 0; i < 40 && !button("放大").disabled; i++) { button("放大").click(); await paint(); }
  check(zoom() === "400%" && button("放大").disabled && !button("缩小").disabled, "达到 400% 禁用放大，仍可缩小");
  button("放大").click(); await paint();
  check(zoom() === "400%", "到达上限后不会继续放大");
  button("缩小").click(); await paint();
  check(!button("放大").disabled, "离开上限后放大恢复可用");
  for (let i = 0; i < 40 && !button("缩小").disabled; i++) { button("缩小").click(); await paint(); }
  check(zoom() === "3%" && button("缩小").disabled && !button("放大").disabled, "达到 3% 禁用缩小，仍可放大");
  button("缩小").click(); await paint();
  check(zoom() === "3%" && ratioWidth() === fixedWidth, "下限不可继续缩小，比例从三位变一位也不挤动布局");
  button("100% 查看").click(); await paint();
  check(zoom() === "100%" && !button("缩小").disabled && !button("放大").disabled, "100% 一键恢复实际比例，同时解除缩放极限禁用");
  button("适配画布").click(); await paint();
  check(!button("适配画布").textContent && !!button("适配画布").querySelector("svg") && button("适配画布").parentElement!.textContent!.includes("完整显示图片并居中") && Number(zoom()!.replace("%", "")) <= 100 && button("撤销").disabled && button("消除笔").getAttribute("aria-pressed") === "true", "图标适配入口保留说明，查看操作不产生历史或切换工具");
} catch (error) { reports.push(`FAIL ${(error as Error).message}`); }
finally { document.getElementById("results")!.textContent = reports.join("\n"); }
